import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'English' | 'Arabic' | 'Amharic' | 'Oromo';

type TranslationStrings = (typeof translations)[Language] & { [key: string]: string };

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  translations: TranslationStrings;
}

const translations = {
  English: {
    dashboard: 'Dashboard',
    myChildren: 'My Children',
    quranProgress: 'Quran Progress',
    attendance: 'Attendance',
    homework: 'Homework',
    examsResults: 'Exams & Results',
    classSchedule: 'Class Schedule',
    recitationAudio: 'Recitation Audio',
    messagesChat: 'Messages / Chat',
    profileSettings: 'Profile Settings',
    search: 'Search curriculum, teachers...',
    totalChildren: 'Total Children',
    activeClasses: 'Active Classes',
    attendanceRate: 'Attendance Rate',
    avgMemorization: 'Avg Memorization',
    pendingHomework: 'Pending HW',
    nextExam: 'Next Exam',
    childrenOverview: 'Children Overview',
    viewAllProfiles: 'View All Profiles',
    teacher: 'Teacher',
    memorization: 'Memorization',
    currentSurah: 'Current Surah',
    attendanceLog: 'Attendance Log',
    progressDetails: 'Progress Details',
    messages: 'Messages',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    parentPortal: 'Parent Portal',
    primaryGuardian: 'Primary Guardian',
    learningTime: 'Learning Time',
    totalHours: 'Total Hours',
    sessions: 'Sessions',
    avgMinPerSession: 'Avg Min/Session',
    totalMinutes: 'Total Minutes',
    todaysSchedule: "Today's Schedule",
    joinLink: 'Join Link',
    openClassSchedule: 'Open Class Schedule',
    recentFeedbacks: 'Recent Feedbacks',
    viewRemarksHistory: 'View Remarks History',
    childrenProfiles: 'Children Profiles',
    childrenProfilesDesc: 'Detailed cards and active program paths for registered siblings.',
    selectChild: 'Select Child:',
    studentId: 'Student ID:',
    level: 'Level:',
    currentMilestoneSurah: 'Current Milestone Surah:',
    lastStudied: 'Last studied:',
    instructor: 'Instructor:',
    juzProgress: 'Juz Progress',
    remarksLog: 'Remarks & Lessons Log',
    remarksBy: 'Remarks by',
    recentDailyLogs: 'Recent Daily Logs',
    noDailyLogs: 'No daily progress logged yet.',
    tajweedTip: 'Tajweed Tip',
    automatedAttendanceLog: 'Automated Attendance Log',
    attendanceDesc: 'Synchronized automatically in real-time when student joins/leaves online meeting links.',
    averageAttendance: 'Average Attendance',
    lateArrivals: 'Late Arrivals',
    absentSessions: 'Absent Sessions',
    leftEarly: 'Left Early',
    attendanceHistory: 'Attendance History',
    date: 'Date',
    classSession: 'Class Session',
    status: 'Status',
    joinTime: 'Join Time',
    leaveTime: 'Leave Time',
    studentDuration: 'Student Duration',
    teacherDuration: 'Teacher Duration',
    lateAlert: 'Late Alert',
    punctual: 'Punctual',
    missed: 'Missed',
    noAttendanceLogs: 'No attendance logs found in the database.',
    homeworkAssignments: 'Homework Assignments',
    homeworkDesc: 'Review pending homework tasks and child submission statuses.',
    totalHomework: 'Total Homework',
    assigned: 'Assigned',
    pending: 'Pending',
    completed: 'Completed',
    submitted: 'Submitted',
    dueDate: 'Due Date',
    difficulty: 'Difficulty',
    noHomework: 'No homework tasks recorded.',
    examsAndResults: 'Exams & Test Results',
    examsDesc: 'Review official grades, evaluations, and comments from teachers.',
    evaluationLogs: 'Evaluation Logs',
    remarks: 'Remarks:',
    subject: 'Subject:',
    score: 'Score',
    grade: 'Grade',
    passed: 'Passed',
    failed: 'Failed',
    noEvaluations: 'No evaluations recorded yet for',
    classSchedules: 'Class Schedules',
    scheduleDesc: 'Full class slots mapping for all children registered under your guardianship.',
    student: 'Student',
    classTitle: 'Class Title',
    dayOfWeek: 'Day of Week',
    scheduledTime: 'Scheduled Time',
    actions: 'Actions',
    joinRoom: 'Join Room',
    noLinkYet: 'No link yet',
    studentRecitations: 'Student Recitations Audio',
    recitationsDesc: 'Listen to submitted Quran recitation recordings and check teacher scores.',
    evaluationRemarks: 'Evaluation Remarks',
    teacherComments: 'Teacher Comments',
    recitationsComingSoon: 'Recitations feature coming soon.',
    settingsDesc: 'Review and manage your primary guardian details and configurations.',
    guardianFullName: 'Guardian Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    homeAddress: 'Home Address',
    preferredLanguage: 'Preferred Language',
    saveChanges: 'Save Changes',
    notificationSettings: 'Notification Settings',
    notificationsDesc: "Manage push notifications to receive instant updates about your children's classes and activities.",
    arabic: 'العربية',
    amharic: 'አማርኛ',
    oromo: 'Oromoo',
    active: 'Active',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    loading: 'Loading...',
    noData: 'No data available.',
    comingSoon: 'Coming Soon',
  },
  Amharic: {
    dashboard: 'ዳሽቦርድ',
    myChildren: 'እንደተወለዱ',
    quranProgress: 'ቁርአን እድገት',
    attendance: 'መገኘት',
    homework: 'የቤት ስራ',
    examsResults: 'ፈተናዎች እና ውጤቶች',
    classSchedule: 'የክፍል መርሐግብር',
    recitationAudio: 'የቅራኢት ድምጽ',
    messagesChat: 'መልእክቶች / ውይይት',
    profileSettings: 'የመገለጫ ቅንብሮች',
    search: 'ሥርዓተ ትምህርት፣ መምህራን ይፍለጉ...',
    totalChildren: 'ጠቅላላ ልጆች',
    activeClasses: 'ንቁ ክፍሎች',
    attendanceRate: 'የመገኘት መጠን',
    avgMemorization: 'አማካይ የማስታወስ',
    pendingHomework: 'የሚጠብቅ የቤት ስራ',
    nextExam: 'ቀጣይ ፈተና',
    childrenOverview: 'የልጆች አጠቃላይ እይታ',
    viewAllProfiles: 'ሁሉንም መገለጫዎች ይመልከቱ',
    teacher: 'መምህር',
    memorization: 'ማስታወስ',
    currentSurah: 'የአሁኑ ሱራ',
    attendanceLog: 'የመገኘት መዝገብ',
    progressDetails: 'የእድገት ዝርዝሮች',
    messages: 'መልእክቶች',
    profile: 'መገለጫ',
    settings: 'ቅንብሮች',
    logout: 'ውጣ',
    parentPortal: 'የወላጅ ፖርታል',
    primaryGuardian: 'ዋና ሞግዚት',
    learningTime: 'የትምህርት ጊዜ',
    totalHours: 'ጠቅላላ ሰዓታት',
    sessions: 'ክፍለ ጊዜዎች',
    avgMinPerSession: 'አማካይ ደቂቃ/ክፍለ ጊዜ',
    totalMinutes: 'ጠቅላላ ደቂቃዎች',
    todaysSchedule: 'የዛሬ መርሐግብር',
    joinLink: 'ይቀላቀሉ',
    openClassSchedule: 'የክፍል መርሐግብር ይክፈቱ',
    recentFeedbacks: 'የቅርብ ጊዜ አስተያየቶች',
    viewRemarksHistory: 'የአስተያየቶች ታሪክ ይመልከቱ',
    childrenProfiles: 'የልጆች መገለጫዎች',
    childrenProfilesDesc: 'ለተመዘገቡ እህትማማቾች ዝርዝር ካርዶች እና ንቁ የፕሮግራም መንገዶች።',
    selectChild: 'ልጅ ይምረጡ:',
    studentId: 'የተማሪ መለያ:',
    level: 'ደረጃ:',
    currentMilestoneSurah: 'አሁን ያለው ወሳኝ ሱራ:',
    lastStudied: 'የመጨረሻ ጥናት:',
    instructor: 'አስተማሪ:',
    juzProgress: 'የጁዝ እድገት',
    remarksLog: 'አስተያየቶች እና ትምህርቶች መዝገብ',
    remarksBy: 'አስተያየት የሰጡት',
    recentDailyLogs: 'የቅርብ ጊዜ ዕለታዊ መዝገቦች',
    noDailyLogs: 'እስካሁን ምንም ዕለታዊ እድገት አልተመዘገበም።',
    tajweedTip: 'የታጅዊድ ምክር',
    automatedAttendanceLog: 'አውቶማቲክ የመገኘት መዝገብ',
    attendanceDesc: 'ተማሪ የመስመር ላይ ስብሰባ ሲቀላቀል/ሲለቅ በራስ-ሰር በእውነተኛ ጊዜ ይመሳሰላል።',
    averageAttendance: 'አማካይ መገኘት',
    lateArrivals: 'ዘግይተው መምጣት',
    absentSessions: 'ያልተገኙ ክፍለ ጊዜዎች',
    leftEarly: 'ቀድመው መልቀቅ',
    attendanceHistory: 'የመገኘት ታሪክ',
    date: 'ቀን',
    classSession: 'የክፍል ክፍለ ጊዜ',
    status: 'ሁኔታ',
    joinTime: 'የተቀላቀሉበት ሰዓት',
    leaveTime: 'የለቀቁበት ሰዓት',
    studentDuration: 'የተማሪ ቆይታ',
    teacherDuration: 'የመምህር ቆይታ',
    lateAlert: 'ዘግይተው ማስጠንቀቂያ',
    punctual: 'በሰዓቱ',
    missed: 'አልተገኙም',
    noAttendanceLogs: 'በውሂብ ጎታ ውስጥ ምንም የመገኘት መዝገቦች አልተገኙም።',
    homeworkAssignments: 'የቤት ስራ መመደቦች',
    homeworkDesc: 'የሚጠብቁ የቤት ስራዎችን እና የልጅ ማስረከቢያ ሁኔታዎችን ይገምግሙ።',
    totalHomework: 'ጠቅላላ የቤት ስራ',
    assigned: 'የተሰጠ',
    pending: 'በመጠባበቅ ላይ',
    completed: 'የተጠናቀቀ',
    submitted: 'የቀረበ',
    dueDate: 'የማቅረቢያ ቀን',
    difficulty: 'አስቸጋሪነት',
    noHomework: 'ምንም የቤት ስራ አልተመዘገበም።',
    examsAndResults: 'ፈተናዎች እና ውጤቶች',
    examsDesc: 'ኦፊሴላዊ ውጤቶችን፣ ምዘናዎችን እና የመምህራን አስተያየቶችን ይገምግሙ።',
    evaluationLogs: 'የምዘና መዝገቦች',
    remarks: 'አስተያየቶች:',
    subject: 'ርዕሰ ጉዳይ:',
    score: 'ውጤት',
    grade: 'ክፍል',
    passed: 'አልፈዋል',
    failed: '�ወቀዋል',
    noEvaluations: 'እስካሁን ምንም ምዘና አልተመዘገበም',
    classSchedules: 'የክፍል መርሐግብሮች',
    scheduleDesc: 'በእርስዎ ሞግዚትነት ለተመዘገቡ ሁሉም ልጆች የተሟላ የክፍል ጊዜ ካርታ።',
    student: 'ተማሪ',
    classTitle: 'የክፍል ርዕስ',
    dayOfWeek: 'የሳምንቱ ቀን',
    scheduledTime: 'የታቀደ ጊዜ',
    actions: 'ተግባራት',
    joinRoom: 'ክፍሉን ይቀላቀሉ',
    noLinkYet: 'እስካሁን አገናኝ የለም',
    studentRecitations: 'የተማሪ ቅራኢት ድምጽ',
    recitationsDesc: 'የቀረቡ የቁርአን ቅራኢት ድምጽ ቅጂዎችን ያዳምጡ እና የመምህራን ውጤቶችን ይፈትሹ።',
    evaluationRemarks: 'የምዘና አስተያየቶች',
    teacherComments: 'የመምህር አስተያየቶች',
    recitationsComingSoon: 'የቅራኢት ባህሪ በቅርቡ ይመጣል።',
    settingsDesc: 'የዋና ሞግዚት ዝርዝሮችዎን እና ውቅሮችዎን ይገምግሙ እና ያስተዳድሩ።',
    guardianFullName: 'የሞግዚት ሙሉ ስም',
    emailAddress: 'ኢሜይል አድራሻ',
    phoneNumber: 'ስልክ ቁጥር',
    homeAddress: 'የቤት አድራሻ',
    preferredLanguage: 'የሚመረጥ ቋንቋ',
    saveChanges: 'ለውጦችን አስቀምጥ',
    notificationSettings: 'የማሳወቂያ ቅንብሮች',
    notificationsDesc: 'ስለ ልጆችዎ ክፍሎች እና እንቅስቃሴዎች ፈጣን ዝማኔዎችን ለመቀበል የግፋ ማሳወቂያዎችን ያስተዳድሩ።',
    arabic: 'አረብኛ',
    amharic: 'አማርኛ',
    oromo: 'ኦሮሚኛ',
    active: 'ንቁ',
    high: 'ከፍተኛ',
    medium: 'መካከለኛ',
    low: 'ዝቅተኛ',
    loading: 'በመጫን ላይ...',
    noData: 'ምንም ውሂብ የለም።',
    comingSoon: 'በቅርቡ ይመጣል',
  },
  Oromo: {
    dashboard: 'Daashboorad',
    myChildren: 'Ijoollee Koo',
    quranProgress: "Qur'ana Irratti",
    attendance: 'Dhaabbachuu',
    homework: 'Hoji Manaa',
    examsResults: "Qormaata fi Bu'aa",
    classSchedule: 'Taqsii Kilaasii',
    recitationAudio: "Sagalee Qiraa'aa",
    messagesChat: 'Ergoota / Haasa',
    profileSettings: 'Qindeessaa',
    search: 'Barnoota, barsiisota barbaadi...',
    totalChildren: 'Ijoollee Walii',
    activeClasses: 'Kilaasota Hoji-irraa',
    attendanceRate: 'Haala Dhaabbachuu',
    avgMemorization: 'Giddugalee Yaadannoo',
    pendingHomework: 'Hoji Manaa Eeggachaa',
    nextExam: 'Qormaata Ittaanu',
    childrenOverview: 'Arginsa Ijoollee',
    viewAllProfiles: 'Qindeessaa Hunda Ilaali',
    teacher: 'Barsisaa',
    memorization: 'Yaadannoo',
    currentSurah: 'Suuraa Ammaa',
    attendanceLog: 'Galmee Dhaabbachuu',
    progressDetails: "Bal'ina Fooyyaa",
    messages: 'Ergoota',
    profile: 'Qindeessaa',
    settings: 'Sajoo',
    logout: "Ba'i",
    parentPortal: 'Mana Eega',
    primaryGuardian: 'Eegduu Guddaa',
    learningTime: 'Yeroo Barumsaa',
    totalHours: "Sa'atii Walii",
    sessions: 'Turtii',
    avgMinPerSession: 'Giddugalee Daqiiqaa/Turtti',
    totalMinutes: 'Daqiiqaa Walii',
    todaysSchedule: "Taqsii Har'aa",
    joinLink: 'Linkii Seenuu',
    openClassSchedule: 'Taqsii Kilaasii Ban',
    recentFeedbacks: 'Ilaalcha Dhihoo',
    viewRemarksHistory: 'Seenaa Ilaalchaa Ilaali',
    childrenProfiles: 'Qindeessaa Ijoollee',
    childrenProfilesDesc: 'Kaardiiwwan bal\'aa fi karaa sagantaa hojiirraa jiru firoota galmaa\'aniif.',
    selectChild: 'Mucaa Filadhu:',
    studentId: 'ID Barataa:',
    level: 'Sadarkaa:',
    currentMilestoneSurah: 'Suuraa Gahumsa Ammaa:',
    lastStudied: 'Kan dhumaa barate:',
    instructor: 'Barsisaa:',
    juzProgress: 'Fooyyaa Juz',
    remarksLog: 'Galmee Ilaalchaa fi Barumsaa',
    remarksBy: 'Ilaalchi kan kenne',
    recentDailyLogs: 'Galmee Guyyaa Dhihoo',
    noDailyLogs: 'Guyyaa guyyaan fooyyaa hin galmeeffamne.',
    tajweedTip: 'Gorsa Tajweed',
    automatedAttendanceLog: 'Galmee Dhaabbachuu Of-Duubaa',
    attendanceDesc: 'Yeroo barataan linkii marii online seenu/gadi lakkisuun yeroo dhugaaatti ofuma isaanii walsimsa.',
    averageAttendance: 'Giddugalee Dhaabbachuu',
    lateArrivals: 'Dhuftee Tursiifame',
    absentSessions: 'Turtii Hin Dhaabanne',
    leftEarly: 'Duri Bahe',
    attendanceHistory: 'Seenaa Dhaabbachuu',
    date: 'Guyyaa',
    classSession: 'Turtii Kilaasii',
    status: 'Haala',
    joinTime: 'Yeroo Seene',
    leaveTime: 'Yeroo Bahe',
    studentDuration: 'Turii Barataa',
    teacherDuration: 'Turii Barsiisaa',
    lateAlert: 'Rakkoo Tursiifamaa',
    punctual: 'Yeroo sirrii',
    missed: 'Hin Dhaabanne',
    noAttendanceLogs: 'Galmee dhaabbachuu databaasii keessatti hin argamne.',
    homeworkAssignments: 'Hoji Manaa Kennaman',
    homeworkDesc: 'Hoji manaa eeggachaa jiran fi haala dhiyeessaa ijoollee ilaali.',
    totalHomework: 'Hoji Manaa Walii',
    assigned: 'Kenname',
    pending: 'Eeggachaa',
    completed: 'Xumurame',
    submitted: 'Dhiyeffame',
    dueDate: 'Guyyaa Xumuraa',
    difficulty: 'Rakkoo',
    noHomework: 'Hoji manaa tokko iyyuu hin galmeeffamne.',
    examsAndResults: "Qormaata fi Bu'aa",
    examsDesc: "Bu'aa ofisyaalii, madaalii, fi yaada barsiisotaa ilaali.",
    evaluationLogs: 'Galmee Madaalii',
    remarks: 'Yaada:',
    subject: 'Mataduree:',
    score: 'Qabxii',
    grade: 'Sadarkaa',
    passed: 'Darbee',
    failed: 'Kuftaa',
    noEvaluations: 'Madaalii tokko iyyuu hin galmeeffamne',
    classSchedules: 'Taqsii Kilaasii',
    scheduleDesc: 'Ijoollee hunda eegumsa kee jala galmaa\'aniif taqsii kilaasii guutuu.',
    student: 'Barataa',
    classTitle: 'Mata Duree Kilaasii',
    dayOfWeek: 'Guyyaa Torbanii',
    scheduledTime: 'Yeroo Karoorfame',
    actions: 'Gochaawwan',
    joinRoom: 'Kilaasii Seeni',
    noLinkYet: 'Linkii hin jiru',
    studentRecitations: "Sagalee Qiraa'a Barataa",
    recitationsDesc: "Sagalee qiraa'a Qur'aanaa dhiyaate dhaggeeffadhuutii qabxii barsiisaa ilaali.",
    evaluationRemarks: 'Ilaalcha Madaalii',
    teacherComments: 'Yaada Barsiisaa',
    recitationsComingSoon: 'Gochaa Qiraa\'a fuula dura dhufa.',
    settingsDesc: 'Ibsa fi qindeessaa eegduu guddaa kee ilaalii bulchi.',
    guardianFullName: 'Maqaa Guutuu Eegduu',
    emailAddress: 'Imeelii',
    phoneNumber: 'Lakkoofsa Bilbilaa',
    homeAddress: 'Teessoo Manaa',
    preferredLanguage: 'Afaan Filatame',
    saveChanges: 'Jijjiirama Olkaayi',
    notificationSettings: 'Qindeessaa Beeksisa',
    notificationsDesc: 'Beeksisa diimaa yeroo tokkotti olaantuu ijoollee kee fi gochaalee isaanii argachuuf bulchi.',
    arabic: 'Arabiffaa',
    amharic: 'Afaan Amaaraa',
    oromo: 'Oromoo',
    active: 'Hojiirraa',
    high: "Ol'aanaa",
    medium: 'Giddugaleessa',
    low: 'Gadi',
    loading: "Fe'iiraa...",
    noData: 'Ragaa hin jiru.',
    comingSoon: 'Fuula Dura Dhufa',
  },
  Arabic: {
    dashboard: 'لوحة التحكم',
    myChildren: 'أطفالي',
    quranProgress: 'تقدم القرآن',
    attendance: 'الحضور',
    homework: 'الواجبات',
    examsResults: 'الامتحانات والنتائج',
    classSchedule: 'جدول الفصل',
    recitationAudio: 'تسجيلات التلاوة',
    messagesChat: 'الرسائل / المحادثة',
    profileSettings: 'إعدادات الملف الشخصي',
    search: 'ابحث في المناهج، المعلمين...',
    totalChildren: 'إجمالي الأطفال',
    activeClasses: 'الفصول النشطة',
    attendanceRate: 'نسبة الحضور',
    avgMemorization: 'متوسط الحفظ',
    pendingHomework: 'الواجبات المعلقة',
    nextExam: 'الامتحان القادم',
    childrenOverview: 'نظرة عامة على الأطفال',
    viewAllProfiles: 'عرض جميع الملفات',
    teacher: 'المعلم',
    memorization: 'الحفظ',
    currentSurah: 'السورة الحالية',
    attendanceLog: 'سجل الحضور',
    progressDetails: 'تفاصيل التقدم',
    messages: 'الرسائل',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    parentPortal: 'بوابة ولي الأمر',
    primaryGuardian: 'ولي الأمر الأساسي',
    learningTime: 'وقت التعلم',
    totalHours: 'إجمالي الساعات',
    sessions: 'الجلسات',
    avgMinPerSession: 'متوسط الدقائق/الجلسة',
    totalMinutes: 'إجمالي الدقائق',
    todaysSchedule: 'جدول اليوم',
    joinLink: 'رابط الانضمام',
    openClassSchedule: 'فتح جدول الفصل',
    recentFeedbacks: 'التعليقات الأخيرة',
    viewRemarksHistory: 'عرض سجل الملاحظات',
    childrenProfiles: 'ملفات الأطفال',
    childrenProfilesDesc: 'بطاقات مفصلة ومسارات البرامج النشطة للأشقاء المسجلين.',
    selectChild: 'اختر طفلاً:',
    studentId: 'رقم الطالب:',
    level: 'المستوى:',
    currentMilestoneSurah: 'سورة الإنجاز الحالية:',
    lastStudied: 'آخر دراسة:',
    instructor: 'المعلم:',
    juzProgress: 'تقدم الجزء',
    remarksLog: 'سجل الملاحظات والدروس',
    remarksBy: 'ملاحظات من',
    recentDailyLogs: 'السجلات اليومية الأخيرة',
    noDailyLogs: 'لم يتم تسجيل أي تقدم يومي بعد.',
    tajweedTip: 'نصيحة تجويد',
    automatedAttendanceLog: 'سجل الحضور الآلي',
    attendanceDesc: 'يتم المزامنة تلقائياً في الوقت الفعلي عند انضمام/مغادرة الطالب للاجتماع.',
    averageAttendance: 'متوسط الحضور',
    lateArrivals: 'الوصول المتأخر',
    absentSessions: 'جلسات الغياب',
    leftEarly: 'المغادرة المبكرة',
    attendanceHistory: 'سجل الحضور',
    date: 'التاريخ',
    classSession: 'جلسة الفصل',
    status: 'الحالة',
    joinTime: 'وقت الانضمام',
    leaveTime: 'وقت المغادرة',
    studentDuration: 'مدة الطالب',
    teacherDuration: 'مدة المعلم',
    lateAlert: 'تنبيه التأخير',
    punctual: 'في الموعد',
    missed: 'غائب',
    noAttendanceLogs: 'لم يتم العثور على سجلات حضور.',
    homeworkAssignments: 'الواجبات المنزلية',
    homeworkDesc: 'مراجعة الواجبات المعلقة وحالات تقديم الطفل.',
    totalHomework: 'إجمالي الواجبات',
    assigned: 'مسند',
    pending: 'معلق',
    completed: 'مكتمل',
    submitted: 'مقدم',
    dueDate: 'تاريخ الاستحقاق',
    difficulty: 'الصعوبة',
    noHomework: 'لم يتم تسجيل أي واجبات منزلية.',
    examsAndResults: 'الامتحانات والنتائج',
    examsDesc: 'مراجعة الدرجات الرسمية والتقييمات وتعليقات المعلمين.',
    evaluationLogs: 'سجل التقييمات',
    remarks: 'ملاحظات:',
    subject: 'المادة:',
    score: 'الدرجة',
    grade: 'التقدير',
    passed: 'ناجح',
    failed: 'راسب',
    noEvaluations: 'لم يتم تسجيل أي تقييمات بعد لـ',
    classSchedules: 'جداول الفصل',
    scheduleDesc: 'خرائط كاملة لمواعيد الفصل لجميع الأطفال المسجلين تحت وصايتك.',
    student: 'الطالب',
    classTitle: 'عنوان الفصل',
    dayOfWeek: 'يوم الأسبوع',
    scheduledTime: 'الوقت المحدد',
    actions: 'الإجراءات',
    joinRoom: 'انضم للغرفة',
    noLinkYet: 'لا يوجد رابط بعد',
    studentRecitations: 'تسجيلات تلاوة الطالب',
    recitationsDesc: 'استمع إلى تسجيلات تلاوة القرآن المقدمة وتحقق من درجات المعلم.',
    evaluationRemarks: 'ملاحظات التقييم',
    teacherComments: 'تعليقات المعلم',
    recitationsComingSoon: 'ميزة التسجيلات قادمة قريباً.',
    settingsDesc: 'مراجعة وإدارة تفاصيل وإعدادات ولي الأمر الأساسي.',
    guardianFullName: 'الاسم الكامل لولي الأمر',
    emailAddress: 'البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف',
    homeAddress: 'العنوان',
    preferredLanguage: 'اللغة المفضلة',
    saveChanges: 'حفظ التغييرات',
    notificationSettings: 'إعدادات الإشعارات',
    notificationsDesc: 'إدارة الإشعارات الفورية لتلقي تحديثات فورية حول فصول وأنشطة أطفالك.',
    arabic: 'العربية',
    amharic: 'الأمهرية',
    oromo: 'الأورومو',
    active: 'نشط',
    high: 'عالي',
    medium: 'متوسط',
    low: 'منخفض',
    loading: 'جارٍ التحميل...',
    noData: 'لا توجد بيانات متاحة.',
    comingSoon: 'قريباً',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('parentLanguage');
      if (saved) return saved as Language;
    }
    return 'English';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('parentLanguage', lang);
      document.documentElement.lang = lang.toLowerCase();
    }
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, translations: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
