/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as Teacher_dashboardRouteImport } from './routes/teacher_dashboard'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as Student_dashboardRouteImport } from './routes/student_dashboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as Parent_dashboardRouteImport } from './routes/parent_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersCreateRouteImport } from './routes/teachers_.create'
import { Route as TeachersIdRouteImport } from './routes/teachers_.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const Teacher_dashboardRoute = Teacher_dashboardRouteImport.update({
  id: '/teacher_dashboard',
  path: '/teacher_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const Student_dashboardRoute = Student_dashboardRouteImport.update({
  id: '/student_dashboard',
  path: '/student_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const Parent_dashboardRoute = Parent_dashboardRouteImport.update({
  id: '/parent_dashboard',
  path: '/parent_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersCreateRoute = TeachersCreateRouteImport.update({
  id: '/teachers_/create',
  path: '/teachers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIdRoute = TeachersIdRouteImport.update({
  id: '/teachers_/$id',
  path: '/teachers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/parent_dashboard': typeof Parent_dashboardRoute
  '/parents': typeof ParentsRoute
  '/register': typeof RegisterRoute
  '/student_dashboard': typeof Student_dashboardRoute
  '/students': typeof StudentsRoute
  '/teacher_dashboard': typeof Teacher_dashboardRoute
  '/teachers': typeof TeachersRoute
  '/users': typeof UsersRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/create': typeof TeachersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/parent_dashboard': typeof Parent_dashboardRoute
  '/parents': typeof ParentsRoute
  '/register': typeof RegisterRoute
  '/student_dashboard': typeof Student_dashboardRoute
  '/students': typeof StudentsRoute
  '/teacher_dashboard': typeof Teacher_dashboardRoute
  '/teachers': typeof TeachersRoute
  '/users': typeof UsersRoute
  '/teachers/$id': typeof TeachersIdRoute
  '/teachers/create': typeof TeachersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/parent_dashboard': typeof Parent_dashboardRoute
  '/parents': typeof ParentsRoute
  '/register': typeof RegisterRoute
  '/student_dashboard': typeof Student_dashboardRoute
  '/students': typeof StudentsRoute
  '/teacher_dashboard': typeof Teacher_dashboardRoute
  '/teachers': typeof TeachersRoute
  '/users': typeof UsersRoute
  '/teachers_/$id': typeof TeachersIdRoute
  '/teachers_/create': typeof TeachersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/parent_dashboard'
    | '/parents'
    | '/register'
    | '/student_dashboard'
    | '/students'
    | '/teacher_dashboard'
    | '/teachers'
    | '/users'
    | '/teachers/$id'
    | '/teachers/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/parent_dashboard'
    | '/parents'
    | '/register'
    | '/student_dashboard'
    | '/students'
    | '/teacher_dashboard'
    | '/teachers'
    | '/users'
    | '/teachers/$id'
    | '/teachers/create'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/parent_dashboard'
    | '/parents'
    | '/register'
    | '/student_dashboard'
    | '/students'
    | '/teacher_dashboard'
    | '/teachers'
    | '/users'
    | '/teachers_/$id'
    | '/teachers_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  Parent_dashboardRoute: typeof Parent_dashboardRoute
  ParentsRoute: typeof ParentsRoute
  RegisterRoute: typeof RegisterRoute
  Student_dashboardRoute: typeof Student_dashboardRoute
  StudentsRoute: typeof StudentsRoute
  Teacher_dashboardRoute: typeof Teacher_dashboardRoute
  TeachersRoute: typeof TeachersRoute
  UsersRoute: typeof UsersRoute
  TeachersIdRoute: typeof TeachersIdRoute
  TeachersCreateRoute: typeof TeachersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher_dashboard': {
      id: '/teacher_dashboard'
      path: '/teacher_dashboard'
      fullPath: '/teacher_dashboard'
      preLoaderRoute: typeof Teacher_dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student_dashboard': {
      id: '/student_dashboard'
      path: '/student_dashboard'
      fullPath: '/student_dashboard'
      preLoaderRoute: typeof Student_dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent_dashboard': {
      id: '/parent_dashboard'
      path: '/parent_dashboard'
      fullPath: '/parent_dashboard'
      preLoaderRoute: typeof Parent_dashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers_/create': {
      id: '/teachers_/create'
      path: '/teachers/create'
      fullPath: '/teachers/create'
      preLoaderRoute: typeof TeachersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers_/$id': {
      id: '/teachers_/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof TeachersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  Parent_dashboardRoute: Parent_dashboardRoute,
  ParentsRoute: ParentsRoute,
  RegisterRoute: RegisterRoute,
  Student_dashboardRoute: Student_dashboardRoute,
  StudentsRoute: StudentsRoute,
  Teacher_dashboardRoute: Teacher_dashboardRoute,
  TeachersRoute: TeachersRoute,
  UsersRoute: UsersRoute,
  TeachersIdRoute: TeachersIdRoute,
  TeachersCreateRoute: TeachersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
